vich_uploader:
    db_driver: orm

    mappings:
        chef_images:
         uri_prefix: /images/images_chef
         upload_destination: '%kernel.project_dir%/public/images/images_chef'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         delete_on_remove: true
         delete_on_update: true
         inject_on_load: false
          

        menu_images:
         uri_prefix: /images/menu_images
         upload_destination: '%kernel.project_dir%/public/images/menu_images'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         delete_on_remove: true
         delete_on_update: true
         inject_on_load: false

        product_images:
         uri_prefix: /images/product_images
         upload_destination: '%kernel.project_dir%/public/images/product_images'
         namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
         delete_on_remove: true
         delete_on_update: true
         inject_on_load: false
